### ISSUE TITLE
Add hierarchical prompt select

### ISSUE THREAD

**Issue by Arnaud73** [c4spar/deno-cliffy#584] opened 2023-04-14 11:25 UTC
I've been using Cliffy for a while on business related help tool. It started little but grew quite a bit.

I'm doing quite a use of prompts for selecting multiple elements. At first, the application was simple and there was not a lot to chose from, but those lists of choices grew larger, which make them less convenient to use.

I would like to organize my selects as a tree instead of a list so that finding the right element is quicker (let's say selects are organized by category, then the select would present the category first and once selected, the items related to this category).

**Comment by c4spar** [comment] 2023-04-25 21:35
duplicate of https://github.com/c4spar/deno-cliffy/issues/382

@Arnaud73 mult level select and checkbox prompts are already implemented in this PR https://github.com/c4spar/deno-cliffy/pull/445. If you want you can have a look and try it out. I will merge it soon.

**Closed** 2023-04-25 21:36 UTC
