### ISSUE TITLE
Pointers and icons are bugged

### ISSUE THREAD

**Issue by hades3729** [c4spar/deno-cliffy#372] opened 2022-05-08 12:33 UTC
![image](https://user-images.githubusercontent.com/89024660/167296235-bc85998a-d0c4-4744-b486-de2169dbce90.png)
![image](https://user-images.githubusercontent.com/89024660/167296239-e32d3ef0-ba3d-4a5f-92c5-d9dd38d7488d.png)

After using Cliffy normally, I realized it had an update. I then updated Cliffy and Deno, and now whether it's with the checkbox, the list, or anything else that uses the pointer or any icons, they're bugged. I know that this isn't a font issue, but I don't know what caused that

**Comment by c4spar** [comment] 2022-05-08 12:49
Which os are you using? I can not reproduce it on mac.

**Comment by hades3729** [comment] 2022-05-08 12:55
I'm on Windows 10

**Comment by c4spar** [comment] 2022-05-08 13:16
Duplicate of #113

**Closed by c4spar** 2022-05-08 13:16 UTC
